node{
  def gitUrl        = "https://github.com/kodekloudhub/kubernetes-challenges.git"
  def ImageName     = "mohamedayman/nodejs-demo"
  def gitCred 	    = "git"
  def dockerhubCred = "dockerhub"

  try{
  stage('Checkout'){
    git credentialsId: "$gitCred", url: "$gitUrl"
    // tag image with th commit id
    sh "git rev-parse --short HEAD > .git/commit-id"
    imageTag = readFile('.git/commit-id').trim()

  }

  stage('Docker Build, Push'){
    withDockerRegistry([credentialsId: "${dockerhubCred}", url: 'https://index.docker.io/v1/']) {
      sh "docker build -t ${ImageName}:${imageTag} ."
      sh "docker push ${ImageName}:${imageTag}"
        }

    }

   stage('Deploy nodejs App on K8s'){
     sh  script: """
         set +e
         helm install  nodejs --set image.repository=${ImageName} --set image.tag=${imageTag} ./nodejs-k8s
         set -e
         """
         // update to New version
     sh "helm upgrade --wait --recreate-pods --set image.repository=${ImageName} --set image.tag=${imageTag} nodejs ./nodejs-k8s"


   }
     } catch (err) {
      currentBuild.result = 'FAILURE'
    }
}
